### ISSUE TITLE
Does your implementation match the original exactly?

### ISSUE THREAD

**Issue by cdsjjav** [yadrimz/DESIRE#1]
I think that your implementation is great !! Thank you for your sharing.
However, I am not sure your implementation matches the original exactly.
The details of DESIRE described in the original paper are so confusing and too complicated.

**Comment by yadrimz** [comment]
Hey, thanks for your interest!

You are right, this is work in progress that I put on hold a while ago.
For that reason it does not yet match the original exactly. I should update the Readme as it is indeed confusing. The project also relies on an older version of Tensorflow - 1.3.0 if I am not mistaken.

In the mean time, feel free to fork and contribute to completing this implementation.
